---
# Task writes "some stuff" to a predefined path in the workspace git PipelineResource
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test-ansi-2-html
spec:
  steps:
  - name: create-sections
    image: ibmcom/pipeline-base-image
    command: ['/bin/bash']
    args: ['-c', 'echo -e "\e[0Ksection_start:`date +%s`:my_first_section\r\e[0KHeader of the 1st collapsible section"; echo "this line should be hidden when collapsed"; echo -e "\e[0Ksection_end:`date +%s`:my_first_section\r\e[0K"']
  - name: print-ansi-colors
    image: ibmcom/pipeline-base-image
    command: ['/bin/bash']
    args: ['-c', 'curl -sSL "https://gitlab.com/leipert/test-project/-/raw/9e3b85fa9287b8e02dca9a1629aa512f2ef9f338/256-colors.sh" >> colors-256.sh; chmod 755 colors-256.sh; ./colors-256.sh;']
  - name: print-ansi-colors-example
    image: ibmcom/pipeline-base-image
    command: ['/bin/bash']
    args: ['-c', 'curl -sSL "https://raw.githubusercontent.com/stevesoaress/test-ansi/master/npm-install.txt"']
  - name: write-numbers
    image: ubuntu
    command: ['bash']
    args: ['-c', 'for ((i=1;i<=19000;i++)) ; do echo "$i"  ;  done;']
---
# The Output of the first Task (git resource) create-file is given as an `Input`

apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: test-ansi
spec:
  tasks:
  - name: test-ansi-2-html
    taskRef:
      name: test-ansi-2-html
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: test-ansi-run
spec:
  pipelineRef:
    name: test-ansi
  serviceAccountName: 'default'
