---
# Task writes "some stuff" to a predefined path in the workspace git PipelineResource
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: create-file
spec:
  resources:
    inputs:
    - name: workspace
      type: git
      targetPath: damnworkspace
    outputs:
    - name: workspace
      type: git
  steps:
  - name: read-docs-old
    image: ubuntu
    command: ["/bin/bash"]
    args: ['-c', 'ls -la /workspace/damnworkspace/docs/README.md']  # tests that targetpath works
  - name: write-new-stuff
    image: ibmcom/pipeline-base-image
    command: ['/bin/bash']
    args: ['-c', 'curl -sSL "https://gitlab.com/leipert/test-project/-/raw/9e3b85fa9287b8e02dca9a1629aa512f2ef9f338/256-colors.sh" >> colors-256.sh; chmod 755 colors-256.sh; ./colors-256.sh;']
---
# The Output of the first Task (git resource) create-file is given as an `Input`

apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: output-pipeline
spec:
  resources:
  - name: source-repo
    type: git
  tasks:
  - name: first-create-file          # 1. create file
    taskRef:
      name: create-file
    resources:
      inputs:
      - name: workspace
        resource: source-repo
      outputs:
      - name: workspace
        resource: source-repo
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: output-pipeline-run
spec:
  pipelineRef:
    name: output-pipeline
  serviceAccountName: 'default'
